version: '3.8'

services:
  queryforge:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - ./db:/app/db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    restart: always